ethereum_rpc = "https://rpc.ankr.com/eth_hoodi/d2f0692606e2b858a4904e52c1bd966334eb0a117e38dac39facea04c5413270"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

# --- TRAP 1: The original AI Drift Trap (Unchanged) ---
[traps.ai_drift_trap]
name = "AI Drift Trap"
description = "Monitors a numerical value for drift."
path = "out/AIDriftTrap.sol/AIDriftTrap.json"
response_contract = "0x56a0C23256F9234EE79f6c98066B1B92faCb6eb7"
response_function = "handleDrift(string)"
address = "0x1bc6A7EDC145C3A116C646cd81D3a4be1C0a8161"
# --- other params ---
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 100
private_trap = true
whitelist = ["0x018Ecd0cC400C083a74E44a69056D82Adb089F41"]


# --- TRAP 2: Upgraded ChatGPT Analysis Trap ---
[traps.chatgpt_analysis_trap]
name = "Upgraded ChatGPT Analysis Trap"
description = "Uses new sentiment analysis logic."
# This is the address of your existing, registered trap.
address = "0x90f8dEAd8735282F339a1d8E356EF80ab68C902A"

# This is the path to the ABI of your NEW contract with the string parsing logic.
path = "out/SentimentTrap.sol/SentimentTrap.json"

# This is your NEW response contract and function.
response_contract = "0x7Ac5426B0D22786bF96AE5e4eeB9132F2926235F"
response_function = "respond(bytes)"
# --- other params ---
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 1
private_trap = true
whitelist = ["0x018Ecd0cC400C083a74E44a69056D82Adb089F41"]
